sudo: false
language: go
go:
  - 1.8
install:
  - go get github.com/golang/lint/golint
  - go get github.com/mitchellh/gox
script:
  - make test
after_success:
  - make release
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: KLlUjSaqik2Qmj4hsQW6Z989wiHiva8IaKHDqSJw2aDS68PiT8CYFXqoIcdmnytvXL/HIL2ubTR8wriM3nqeYEBvlVpWm3wrgUdu/0AKN1/StUoDlvqk74pKk3KIOH/MynRrQR4aOCumK9LHRa6xCsqnPkX1pSUnIzV+s53X+kAdJzmMAUnRkwRHQUy5MBLlmCC0fmthtpN7k2aHpgcUEbNLIdq2LH7wlUl/fAVgXSjO2XJ5OypDfgqeivG8V4QAhOlEZTIO/pAtXrsQyZ50Obs/X5uqkpuQzDsmO6dqhicRjz6FnUIP4/rkgwxOU15SbUhVkBWkUEO8PG5fSwlaNqc1F9TejcJeIbHSAnvrXouTkxxo1ja9wsrilUrmplNRJp4Gzql5CGujhPyvJpcIYHhQTWC6LheXM9fqau4kxtYHIv2dAwXx/vS8ms5c3H/rOPJnWSI6H/b/6AvB+XvaotuRcHQ+vON5uI0oGUy5Ct11+DEK6e73q25Kt7O1PI+PKrEP2iAx2p9WLmQR6Zzcx4h8xaI8+MH7uYcvTdixkYIDuXm47wbeDV1wgSGgeVoG1ALAD465S9E3Ibrof4Kek1Uvr5fjKESj0n9WR52hAC8CyEyhGGu1snFeFKA50KHTglKSkgYwTw05BfAUFQiiGPCeB0TdXNcV2GkMptd4DDI=
  go: 1.8
  file:
    - pkg/darwin-386-replicator
    - pkg/darwin-amd64-replicator§
    - pkg/freebsd-386-replicator
    - pkg/freebsd-amd64-replicator
    - pkg/freebsd-arm-replicator
    - pkg/linux-386-replicator
    - pkg/linux-amd64-replicator
    - pkg/linux-arm-replicator
  skip_cleanup: true
  on:
    tags: true
